### ISSUE TITLE
Scalatra Org?

### ISSUE THREAD

**Issue by aadrian** [gitbucket/scalatra-forms#4]
Hi,

wouldn't be this project under the Scalatra Org https://github.com/scalatra easier to find ?

**Comment by takezoe** [comment]
Yes, that is my long-term plan.

However, this library has some features which aren't suitable to move to the Scalatra organization. We should isolate them at first.

In addition, Scalatra already has command module which covers larger area than this library. Scalatra team would like to separate (or remove) some unimportant modules from the core repository in Scalatra 3.0. I would like to move this library to the Scalatra organization during this process.

**Comment by aadrian** [comment]
@takezoe thanks for clarifying.

**Comment by takezoe** [comment]
Merged in Scalatra 2.6!
